nodeLinker: node-modules

packageExtensions:
  "@storybook/angular@*":
    peerDependenciesMeta:
      "@angular-devkit/architect":
        optional: true
      "@angular-devkit/core":
        optional: true
  "@storybook/blocks@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@storybook/addon-links@*":
    peerDependenciesMeta:
      react:
        optional: true
  "css-loader@*":
    peerDependenciesMeta:
      webpack:
        optional: true
  "style-loader@*":
    peerDependenciesMeta:
      webpack:
        optional: true
